### ISSUE TITLE
Mod Locate!

### ISSUE THREAD

**Issue by duarte-gui** [FelixDai/DoNotStarveTogether_ServerShell#1]
Hi!

I'm try to add a mo but, cannot complete
![image](https://user-images.githubusercontent.com/55766751/142092108-489128d9-c896-48e9-8bda-1afcb6cb57dd.png)

Can U help me?

TY

**Comment by FelixDai** [comment]
Hi, @duarte-gui !
I am sorry the lua script file named "dedicated_server_mods_setup.lua" was written in the .sh file as an absolute path.
Please create a new one in the same directory as the .sh file, then try again.
Thank you for using this script!

**Comment by FelixDai** [comment]
It maybe need new type of file tracking.
